DROP TABLE IF EXISTS Feed;

CREATE TABLE Feed (
  id IDENTITY NOT NULL PRIMARY KEY,
  sourceUrl VARCHAR(250) NOT NULL,
  feedUrl VARCHAR(250) DEFAULT NULL,
  title VARCHAR(250) DEFAULT NULL,
  description NVARCHAR(MAX) DEFAULT NULL,
  publicationDate VARCHAR(250) DEFAULT NULL,
  imageUrl VARCHAR(250) DEFAULT NULL
);